In [7]:
import array

In [8]:
#Each character is corresponding to a specific data type that the array will contain.
array.typecodes

'bBuhHiIlLqQfd'

In [9]:
from array import array
arr = array('u', 'abcdefg')

In [12]:
#Get the Type Code
arr.typecode

'u'

In [13]:
#Get Size of Array Item
arr.itemsize

2

- Python Array uses less memory size than Python List. 
- It loses some flexibility but has less overhead. 
- arrays are a more direct way of accessing data in memory so they are much faster and more efficient.

2. limitations of array package

- only one type of data
- restricted features
- Insertion and deletion is quite difficult in an array.

In [14]:
import numpy as np

In [29]:
##initializes zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
#initializes ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
#Random number, depending on memory condition
np.empty(5)

array([1., 1., 1., 1., 1.])

In [35]:
#5
arr = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
arr
# it calls a function (either lambda or a normal function) to create an ndarray.

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [65]:
#6
arr1 = np.array([[1,2,3],[4,5,6]])

In [63]:
# broadcasting happens whereby each element of the array is added by one in this case
arr1 + 1


array([[2, 3, 4],
       [5, 6, 7]])

In [79]:
#7. as u can see each element in the array gets incremented by 1
for i in range(3):
    arr1 += 1
    print(arr1)

[[10 11 12]
 [13 14 15]]
[[11 12 13]
 [14 15 16]]
[[12 13 14]
 [15 16 17]]


In [85]:
# importing numpy as np
import numpy as np
  
# Create the numpy array
country = np.array(['USA', 'Japan', 'UK', '', 'India', 'China'])
  
# Print the array
print(country)

['USA' 'Japan' 'UK' '' 'India' 'China']


In [87]:

# Assign 'New Zealand' at the place of missing value
country[country == ''] = 'New Zealand'
  
#it will only assign until the max length initialized and cut off the rest
print(country)

['USA' 'Japan' 'UK' 'New Z' 'India' 'China']


In [88]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 + arr2

array([5, 7, 9])

In [89]:
arr1 + 5

array([6, 7, 8])

In [93]:
arr1 + np.array([1,2])
# this will throw an error because dimensions are not matching

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [94]:
arr1 * arr2

array([ 4, 10, 18])

Each array will have n*m dimension, So consider 2 arrays n1 * m1 and n2 * m2 dimensions, for matrix multiplication to occur it is important that m1 and n2 dimensions are the same otherwise the operation will fail

In [95]:
arr1

array([1, 2, 3])

In [100]:
#10
print(arr<=2)
arr1[arr1<=2]

[[ True  True  True]
 [ True  True False]
 [ True False False]]


array([1, 2])

In [101]:
from statistics import stdev
from numpy import std

speed = [32,111,138,28,59,77,97]
print(stdev(speed))

40.87728441264636


In [102]:
print(std(speed))

37.84501153334721


In [113]:
def mean(data):
    n = len(data)
    mean = sum(data) / n
    return mean

def variance(data):
    n = len(data)
   
    mean = sum(data) / n
   
    deviations = [(x - mean) ** 2 for x in data]
    
    variance = sum(deviations) / n
    return variance

def stdev(data):
    import math
    var = variance(data)
    std_dev = math.sqrt(var)
    return std_dev

print(mean(speed))
print(variance(speed))
print(stdev(speed))

77.42857142857143
1432.2448979591834
37.84501153334721


Our custom function will be the slowest followed by the inbuilt stdev from statistics module followed by the one in numpy package

In [114]:
arr = np.asarray([ [[[1, 11], [2, 22], [3, 33]], [[4, 44], [5, 55], [6, 66]]], [ [[7, 77], [8, 88], [9, 99]], [[0, 32], [1, 33], [2, 34] ]] ])

In [116]:
# u can ensure u dont loose dimentionality here if we fill the na values with 0 (values that dont satisfy the condition)
np.where(arr>3, arr, 0)

array([[[[ 0, 11],
         [ 0, 22],
         [ 0, 33]],

        [[ 4, 44],
         [ 5, 55],
         [ 6, 66]]],


       [[[ 7, 77],
         [ 8, 88],
         [ 9, 99]],

        [[ 0, 32],
         [ 0, 33],
         [ 0, 34]]]])